import pyarrow as pa

SILVER_APP_DEATAIL_SCHEMA = pa.schema(
    [
        pa.field(
            "type",
            pa.string(),
            nullable=False,
        ),
        pa.field(
            "name",
            pa.string(),
            nullable=False,
        ),
        pa.field(
            "steam_appid",
            pa.int64(),
            nullable=False,
        ),
        pa.field(
            "detailed_description",
            pa.string(),
            nullable=True,
        ),
        pa.field(
            "short_description",
            pa.string(),
            nullable=True,
        ),
        pa.field(
            "developers",
            pa.list_(
                pa.field(
                    "item",
                    pa.string(),
                    nullable=False,
                )
            ),
            nullable=True,
        ),
        pa.field(
            "platforms",
            pa.struct(
                [
                    pa.field("windows", pa.bool_(), nullable=True),
                    pa.field("mac", pa.bool_(), nullable=True),
                    pa.field("linux", pa.bool_(), nullable=True),
                ]
            ),
            nullable=True,
        ),
        pa.field(
            "metacritic",
            pa.struct(
                [
                    pa.field("score", pa.int64(), nullable=True),
                    pa.field("url", pa.string(), nullable=True),
                ]
            ),
            nullable=True,
        ),
        pa.field(
            "genres",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct(
                        [
                            pa.field(
                                "description",
                                pa.string(),
                                nullable=True,
                            ),
                        ]
                    ),
                    nullable=False,
                )
            ),
            nullable=True,
        ),
        pa.field(
            "categories",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct(
                        [
                            pa.field(
                                "description",
                                pa.string(),
                                nullable=True,
                            ),
                        ]
                    ),
                    nullable=False,
                )
            ),
            nullable=True,
        ),
        pa.field(
            "screenshots",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct(
                        [
                            pa.field(
                                "path_thumbnail",
                                pa.string(),
                                nullable=True,
                            ),
                            pa.field(
                                "path_full",
                                pa.string(),
                                nullable=True,
                            ),
                        ]
                    ),
                    nullable=False,
                )
            ),
            nullable=True,
        ),
        pa.field(
            "release_date",
            pa.date32(),
            nullable=False,
        ),
        pa.field(
            "coming_soon",
            pa.bool_(),
            nullable=True,
        ),
    ]
)
